on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: "Run Test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: "Run Test"
        run: |
          npm ci
          npm run test

  pre-release:
    name: "Pre Release"
    needs: [test]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: "Build"
        run: |
          npm ci
          npm run build:prod

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
