on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: "Run Test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: "CI"
        run: npm ci

      - name: "Run Test"
        run: npm run test



  build:
    name: "Build"
    needs: [test]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: "Clean"
        run: npm run clean

      - name: "Build"
        run: npm run build

  pre-release:
    name: "Pre Release"
    needs: [build]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
