name: "tagged-release"

on: workflow_dispatch

jobs:
  test:
    name: "Run Test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: "Run Test"
        run: |
          npm ci
          npm run test

  npm-publish:
    name: "NPM publish"
    needs: [ test ]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: 'https://registry.npmjs.org'

      - name: "Build"
        run: |
          npm ci
          npm run build:prod

      - name: "Publish to npm"
        run: npm publish
        env:
          CI: true
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  release:
    name: "Release"
    needs: [test, npm-publish]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
